### PR TITLE
Port of appium 1.4 swipe action

### LINKED ISSUE #150: Swipe works incorrect. WaitAction is not perform
Fast swipe, different behavior with Android.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): v5.7.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real 
* Appium CLI or Appium.app|exe: CLI

[Link to Appium logs](https://gist.github.com/HlebHalkouski/b745e1da71177a3f54b92e587ecd589a)

On javaclient@4.0.0 call method IOSDriver.swipe(200, 200, 0, 100, 3)

### PR DESCRIPTION
**Pull request by toejough**
Fixes #150 

swipe action itself taken from lib/devices/ios/uiauto/appium/app.js as removed by commit f4a1b6fcafc51ae830132b27ff0ed44b5e253865.

extra code to get the data for the swipe action taken from other sections of the existing gesture.js in appium-ios-driver.

This is running quite well in my app tests at the moment.

I've tried to match the code style with this PR, but I didn't see any official guidelines for this repo (though I'm happy to meet standards if they are pointed out).

It also doesn't have any added unit tests.  When I ran the existing tests locally, they passed, I think, but the E2E tests definitely didn't.  I'd be happy to add some more unit tests.

### CODE REVIEW

**Comment by imurchie** [comment]
Thanks for this!

You'll need to run `gulp eslint` and fix anything that comes up, or all the tests will fail.

**Comment by toejough** [comment]
ah, will do.  sorry I missed that - it's been a while since I've written in js.

File: lib/commands/gesture.js [hunk 1]
```diff
@@ -114,13 +114,108 @@ helpers.handleTap = async function (gesture) {
...
+    };
+  } else {
+    return secondCoordinates;
+  }
+};
+
+helpers.handleDrag = async function (gestures) {
+  // get gestures
+  let press = gestures[0];
+  this.validateGestureType(press, 'press');
```
Comment (imurchie) [inline lib/commands/gesture.js]: What is the point of these checks? This code is only ever called if the `isDrag` check has already passed, so these three checks are guaranteed to pass.

File: lib/commands/gesture.js [hunk 2]
```diff
@@ -114,13 +114,108 @@ helpers.handleTap = async function (gesture) {
...
+  let wait = gestures[1];
+  this.validateGestureType(wait, 'wait');
+  let moveTo = gestures[2];
+  this.validateGestureType(moveTo, 'moveTo');
+
+  // get drag data
+  let pressCoordinates = await this.getCoordinates(press);
+  let duration = (parseInt(wait.options.ms) / 1000);
```
Comment (imurchie) [inline lib/commands/gesture.js]: `parseInt` needs a second parameter, `10`, otherwise the behavior is unpredictable.

```js
let duration = parseInt(wait.options.ms, 10) / 1000;
```

**Comment by imurchie** [comment]
A couple of comments. But looks good overall! Thanks for taking this on!

File: lib/commands/gesture.js (hunk 1 above)
Comment (toejough) [inline lib/commands/gesture.js]: they're just defensive - there's nothing stopping anyone from calling handleDrag with the wrong parameters later, and this makes sure that specifically, the gestures `handleDrag` actually uses are the correct gestures.

Could accomplish a similar thing with less code if `handleDrag` just called `isDrag(gestures)` at the top.  You'd get an error if there were greater/less than 4 gestures and the last one wasn't `release`.  I didn't do that because the function doesn't actually need those guarantees in order to generate the command it's supposed to generate.

**Comment by toejough** [comment]
cool - I should be able to get the changes in today.  Do you want changes to the validation code in `handleDrag`?

**Comment by imurchie** [comment]
I don't think it's necessary. Users don't call any of this code, so it is defending against other developers on the system.

**Comment by imurchie** [comment]
This looks good! One last thing to do is to squash into a single commit. Then we can get to merging!

**Comment by toejough** [comment]
squashed!  I just signed the contributor agreement from the main appium project, too.

I left the original commit message - let me know if it needs to be rewritten with any particular data/wording.

**Comment by imurchie** [comment]
Thank you for doing this! It's great!

**Comment by imurchie** [comment]
Published in `appium-ios-driver@1.12.11`.

**Comment by toejough** [comment]
Whoohoo!  happy to have been able to contribute!
